import React from 'react';

export default function SelectBox({ onChange, change }) {
  return (
    <select className="Select-box" onChange={onChange}>
      <option value="tenguy">10 Guy</option>
      <option value="afraid">Afraid to Ask Andy</option>
      <option value="apcr">Almost Politically Correct Redneck</option>
      <option value="older">An Older Code Sir, But It Checks Out</option>
      <option value="aag">Ancient Aliens Guy</option>
      <option value="atis">And Then I Said</option>
      <option value="tried">At Least You Tried</option>
      <option value="biw">Baby Insanity Wolf</option>
      <option value="stew">Baby, You've Got a Stew Going</option>
      <option value="blb">Bad Luck Brian</option>
      <option value="bihw">But It's Honest Work</option>
      <option value="kermit">But That's None of My Business</option>
      <option value="bd">Butthurt Dweller</option>
      <option value="ch">Captain Hindsight</option>
      <option value="cbg">Comic Book Guy</option>
      <option value="wonka">Condescending Wonka</option>
      <option value="cb">Confession Bear</option>
      <option value="gandalf">Confused Gandalf</option>
      <option value="keanu">Conspiracy Keanu</option>
      <option value="cryingfloor">Crying on Floor</option>
      <option value="dsm">Dating Site Murderer</option>
      <option value="disastergirl">Disaster Girl</option>
      <option value="live">Do It Live!</option>
      <option value="ants">Do You Want Ants?</option>
      <option value="doge">Doge</option>
      <option value="trump">Donald Trump</option>
      <option value="drake">Drakeposting</option>
      <option value="ermg">Ermahgerd</option>
      <option value="facepalm">Facepalm</option>
      <option value="feelsgood">Feels Good</option>
      <option value="firsttry">First Try!</option>
      <option value="fwp">First World Problems</option>
      <option value="fa">Forever Alone</option>
      <option value="fbf">Foul Bachelor Frog</option>
      <option value="fmr">Fuck Me, Right?</option>
      <option value="fry">Futurama Fry</option>
      <option value="ggg">Good Guy Greg</option>
      <option value="grumpycat">Grumpy Cat</option>
      <option value="harold">Hide the Pain Harold</option>
      <option value="hipster">Hipster Barista</option>
      <option value="icanhas">I Can Has Cheezburger?</option>
      <option value="crazypills">I Feel Like I'm Taking Crazy Pills</option>
      <option value="mw">I Guarantee It</option>
      <option value="noidea">I Have No Idea What I'm Doing</option>
      <option value="regret">I Immediately Regret This Decision!</option>
      <option value="boat">I Should Buy a Boat Cat</option>
      <option value="hagrid">I Should Not Have Said That</option>
      <option value="sohappy">I Would Be So Happy</option>
      <option value="captain">I am the Captain Now</option>
      <option value="bender">I'm Going to Build My Own Theme Park</option>
      <option value="inigo">Inigo Montoya</option>
      <option value="iw">Insanity Wolf</option>
      <option value="ackbar">It's A Trap!</option>
      <option value="happening">It's Happening</option>
      <option value="joker">It's Simple, Kill the Batman</option>
      <option value="ive">Jony Ive Redesigns Things</option>
      <option value="jd">Joseph Ducreux / Archaic Rap</option>
      <option value="ll">Laughing Lizard</option>
      <option value="lrv">Laundry Room Viking</option>
      <option value="leo">Leo Strutting</option>
      <option value="away">Life... Finds a Way</option>
      <option value="morpheus">Matrix Morpheus</option>
      <option value="mb">Member Berries</option>
      <option value="badchoice">Milk Was a Bad Choice</option>
      <option value="mini-keanu">Mini Keanu Reeves</option>
      <option value="mmm">Minor Mistake Marvin</option>
      <option value="spongebob">Mocking Spongebob</option>
      <option value="soup-nazi">No Soup for You / Soup Nazi</option>
      <option value="jetpack">Nothing To Do Here</option>
      <option value="imsorry">Oh, I'm Sorry, I Thought This Was America</option>
      <option value="red">Oh, Is That What We're Going to Do Today?</option>
      <option value="mordor">One Does Not Simply Walk into Mordor</option>
      <option value="oprah">Oprah You Get a Car</option>
      <option value="oag">Overly Attached Girlfriend</option>
      <option value="remembers">Pepperidge Farm Remembers</option>
      <option value="persian">Persian Cat Room Guardian</option>
      <option value="philosoraptor">Philosoraptor</option>
      <option value="jw">Probably Not a Good Idea</option>
      <option value="patrick">Push it somewhere else Patrick</option>
      <option value="rollsafe">Roll Safe</option>
      <option value="sad-obama">Sad Barack Obama</option>
      <option value="sad-clinton">Sad Bill Clinton</option>
      <option value="sadfrog">Sad Frog / Feels Bad Man</option>
      <option value="sad-bush">Sad George Bush</option>
      <option value="sad-biden">Sad Joe Biden</option>
      <option value="sad-boehner">Sad John Boehner</option>
      <option value="saltbae">Salt Bae</option>
      <option value="sarcasticbear">Sarcastic Bear</option>
      <option value="dwight">Schrute Facts</option>
      <option value="sb">Scumbag Brain</option>
      <option value="ss">Scumbag Steve</option>
      <option value="soa">Seal of Approval</option>
      <option value="sf">Sealed Fate</option>
      <option value="dodgson">See? Nobody Cares</option>
      <option value="money">Shut Up and Take My Money!</option>
      <option value="snek">Skeptical Snake</option>
      <option value="sk">Skeptical Third World Kid</option>
      <option value="sohot">So Hot Right Now</option>
      <option value="nice">So I Got That Goin' For Me, Which is Nice</option>
      <option value="awesome-awkward">Socially Awesome Awkward Penguin</option>
      <option value="awesome">Socially Awesome Penguin</option>
      <option value="awkward-awesome">Socially Awkward Awesome Penguin</option>
      <option value="awkward">Socially Awkward Penguin</option>
      <option value="stop-it">Stop It, Get Some Help</option>
      <option value="fetch">Stop Trying to Make Fetch Happen</option>
      <option value="success">Success Kid</option>
      <option value="scc">Sudden Clarity Clarence</option>
      <option value="ski">Super Cool Ski Instructor</option>
      <option value="aint-got-time-text">
        Sweet Brown / Ain't Nobody Got Time For That
      </option>
      <option value="officespace">That Would Be Great</option>
      <option value="interesting">The Most Interesting Man in the World</option>
      <option value="toohigh">The Rent Is Too Damn High</option>
      <option value="bs">This is Bull, Shark</option>
      <option value="fine">This is Fine</option>
      <option value="sparta">This is Sparta!</option>
      <option value="ugandanknuck">Ugandan Knuckles</option>
      <option value="puffin">Unpopular opinion puffin</option>
      <option value="whatyear">What Year Is It?</option>
      <option value="center">What is this, a Center for Ants?!</option>
      <option value="both">Why Not Both?</option>
      <option value="winter">Winter is coming</option>
      <option value="xy">X all the Y</option>
      <option value="buzz">X, X Everywhere</option>
      <option value="yodawg">Xzibit Yo Dawg</option>
      <option value="yuno">Y U NO Guy</option>
      <option value="yallgot">Y'all Got Any More of Them</option>
      <option value="gears">You Know What Really Grinds My Gears?</option>
      <option value="bad">You Should Feel Bad</option>
      <option value="elf">You Sit on a Throne of Lies</option>
      <option value="chosen">You Were the Chosen One!</option>
    </select>
  );
}
